name: Teste & Build & Deploy

on: 
    push:
    pull_request:
        branches: [master]
    workflow_dispatch:
        
jobs:
              
    MontagemDockerIMG-TesteEBuildMVNW-DeployDockerHub:
        runs-on: ubuntu-latest
        steps: 
        
          - 
            name: Checkout
            uses: actions/checkout@v3
            
          - 
            name: Docker Hub Login
            uses: docker/login-action@v2.1.0
            with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
          - 
            name: Setup Docker build
            uses: docker/setup-buildx-action@v2.5.0
            
          - 
            name: Build and push
            uses: docker/build-push-action@v4.0.0
            with:
                context: .
                file: Dockerfile
                push: true
                tags: ${{ vars.DOCKERHUB_USER }}/calangodev:latest
